### PR TITLE
Adds Elunite Add-on

### PR DESCRIPTION
**Pull request by Omnija**

### CODE REVIEW

**Comment by Silverfeelin** [comment]
Thanks for your contribution! I will check the add-on later today.

Do you want to publish it on Steam yourself or do you want me to maintain it? Note that only the author can update the mod even if you add other users as contributors.

**Comment by Silverfeelin** [comment]
Add-on looks good to me. I'm going to replace the preview image with an in-game preview of the add-on in use. Feel free to change it or let me know if you'd like me to use another outfit if you don't like it!

**Comment by Silverfeelin** [comment]
image

**Comment by Sotaeko** [comment]
I will be able to publish/maintain the Elunite Add-on to Steam. Feel free to contact me through github or discord.

**Comment by Silverfeelin** [comment]
Great. I have added the add-on to Wiki and the Steam collection, thanks!

https://steamcommunity.com/sharedfiles/filedetails/?id=1372702541

**Pull request merged**
